import React from 'react';
import type { Metadata, Viewport } from 'next';
import { headers } from 'next/headers';
import './global.css';
import ReactQueryProvider from '../components/ReactQueryProvider';
import ZustandProvider from '../providers/ZustandProvider';
import { fetchUserInterestRegion } from './_query/fetchUserRegion';

export const metadata: Metadata = {
  title: '유니메이트 - UniMate',
  description: 'Generated by Team4You',
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const header = headers();

  const authHeader = header.get('Authorization');
  const accessToken = authHeader?.startsWith('Bearer ')
    ? authHeader.substring(7)
    : authHeader;
  const isWebview = header.get('IsWebview') === 'true';

  const userInterestRegion = await fetchUserInterestRegion(accessToken);

  return (
    <html>
      <body>
        <ReactQueryProvider>
          <ZustandProvider
            initialState={{
              accessToken, // 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInByb3ZpZGVyIjoiS0FLQU8iLCJ0eXBlIjoiQUNDRVNTIiwiaWF0IjoxNzQ5OTY5MzI0LCJleHAiOjE3NTc3NDUzMjR9.bDpurCfyQ906gPYbPzEnOkzoZpBxLElwXjKY3rwWj9Q'
              isWebview,
              userInterestRegion,
            }}
          >
            {children}
          </ZustandProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
