import React from 'react';
import type { Metadata, Viewport } from 'next';
import { headers } from 'next/headers';
import './global.css';
import ReactQueryProvider from '../components/ReactQueryProvider';
import ZustandProvider from '../providers/ZustandProvider';
import { fetchUserInterestRegion } from './_query/fetchUserRegion';
import { getInitialCommonData } from 'modules/getInitialCommonData';

export const metadata: Metadata = {
  title: '유니메이트 - UniMate',
  description: 'Generated by Team4You',
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialData = await getInitialCommonData();

  return (
    <html>
      <body>
        <ReactQueryProvider>
          <ZustandProvider initialState={initialData}>
            {children}
          </ZustandProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
